---
driver:
  name: ec2
  region: us-east-1
  instance_type: t2.large
  aws_ssh_key_id: jcava-dev
  security_group_ids: ["sg-7650ac0c", "sg-e964bf98"]

transport:
  ssh_key: ~/.ec2/jcava-dev.pem
  username: centos

provisioner:
  name: chef_solo
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image_id: ami-ae7bfdb8

suites:
  - name: default
    run_list:
      - recipe[nexus_iq_server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
