---
# Copyright:: Copyright (c) 2017-present Sonatype, Inc. Apache License, Version 2.0.
driver:
  name: docker
  use_sudo: false
  network:
    - ["private_network", {ip: "192.168.35.35"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    driver:
      name: docker
      image: centos/systemd
      run_command: /bin/bash -c "/usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid & exec /sbin/init"
      privileged: true
      run_options: -v /sys/fs/cgroup:/sys/fs/cgroup:ro
    excludes: ["ubuntu-16.04"]
    run_list:
      - recipe[nexus_iq_server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
# Cache JDK locally for faster kitchen:
#      java:
#        jdk:
#          '8':
#           x86_64:
#              url: 'http://10.0.2.2:8080/jdk-8u131-linux-x64.tar.gz'
#              checksum: '62b215bdfb48bace523723cdbb2157c665e6a25429c73828a32f00e587301236'
