---
driver:
  name: ec2
  aws_ssh_key_id: chef-test-key
  region: us-east-1
  security_group_ids: ["sg-a4fc5ec1"]
  require_chef_omnibus: true
  subnet_id: subnet-c96f61bd
  instance_type: t2.large

transport:
  ssh_key: ~/.ssh/chef-test-key
  username: centos

provisioner:
  name: chef_solo
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image_id: ami-ae7bfdb8

suites:
  - name: default
    run_list:
      - recipe[nexus_iq_server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
